--------------------------------------------------------
-- Archivo creado  - martes-diciembre-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--Crear las tablas especificadas en el modelo relacional, teniendo en cuenta las reglas de nomenclatura en la creación de las mismas.--
--Establecer las restricciones de clave primaria en cada una de las tablas.--
--Establecer las restricciones de clave externa que sean necesarias.--
--Establecer las restricciones de integridad que se crean convenientes, al menos una de tipo NOT NULL, una de tipo CHECK y una de tipo UNIQUE--
--Crear una vista llamada 'v_departamentos' que muestre los datos de la consulta "SELECT * FROM Departamentos".--
--  DDL for Table COMERCIAL
--------------------------------------------------------

  CREATE TABLE "SYS"."COMERCIAL" 
   (	"DNI" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDOS" VARCHAR2(30 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"BONIFICACION" NUMBER(6,2), 
	"TITULACION" VARCHAR2(50 BYTE), 
	"ID_DEPARTAMENTO" NUMBER, 
	"ID_SUCURSAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "SYS"."DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER(7,0), 
	"ID_SUCURSAL" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYS"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(9 BYTE), 
	"DIRECCIÓN" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(25 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROGRAMADOR
--------------------------------------------------------

  CREATE TABLE "SYS"."PROGRAMADOR" 
   (	"DNI" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"LENGUAJES" VARCHAR2(50 BYTE), 
	"PUESTO" VARCHAR2(50 BYTE), 
	"ID_DEPARTAMENTO" NUMBER, 
	"ID_SUCURSAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROYECTOS
--------------------------------------------------------

  CREATE TABLE "SYS"."PROYECTOS" 
   (	"COD_PROYECTO" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"ID_DEPARTAMENTO" NUMBER(4,0), 
	"ID_SUCURSAL" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROYECTO_CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYS"."PROYECTO_CLIENTE" 
   (	"COD_PROYECTO" NUMBER(10,0), 
	"ID_CLIENTE" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "SYS"."SUCURSAL" 
   (	"ID_SUCURSAL" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.COMERCIAL
SET DEFINE OFF;
REM INSERTING into SYS.DEPARTAMENTO
SET DEFINE OFF;
REM INSERTING into SYS.CLIENTE
SET DEFINE OFF;
REM INSERTING into SYS.PROGRAMADOR
SET DEFINE OFF;
REM INSERTING into SYS.PROYECTOS
SET DEFINE OFF;
REM INSERTING into SYS.PROYECTO_CLIENTE
SET DEFINE OFF;
REM INSERTING into SYS.SUCURSAL
SET DEFINE OFF;

--------------------------------------------------------
--  Constraints for Table COMERCIAL
--------------------------------------------------------

  ALTER TABLE "SYS"."COMERCIAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COMERCIAL" MODIFY ("APELLIDOS" CONSTRAINT "APELLIDOS_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COMERCIAL" MODIFY ("FECHA_NACIMIENTO" CONSTRAINT "FECHA_NACIMIENTO_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COMERCIAL" ADD PRIMARY KEY ("DNI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."COMERCIAL" MODIFY ("TITULACION" CONSTRAINT "TITULACION_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COMERCIAL" ADD CONSTRAINT "BONIFICACION_MINIMA" CHECK (BONIFICACION >600) ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "SYS"."DEPARTAMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPARTAMENTO" MODIFY ("DIRECCION" CONSTRAINT "DIRECCION_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYS"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."CLIENTE" ADD CONSTRAINT "CLIENTE_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROGRAMADOR
--------------------------------------------------------

  ALTER TABLE "SYS"."PROGRAMADOR" MODIFY ("LENGUAJES" CONSTRAINT "LENGUAJES_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROGRAMADOR" MODIFY ("PUESTO" CONSTRAINT "PUESTO_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROGRAMADOR" ADD CONSTRAINT "PROGRAMADOR_PK" PRIMARY KEY ("DNI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROYECTOS
--------------------------------------------------------

  ALTER TABLE "SYS"."PROYECTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROYECTOS" MODIFY ("DESCRIPCION" CONSTRAINT "DESCRIPCION_NNULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROYECTOS" ADD CONSTRAINT "PROYECTOS_PK" PRIMARY KEY ("COD_PROYECTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROYECTO_CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYS"."PROYECTO_CLIENTE" MODIFY ("COD_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROYECTO_CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROYECTO_CLIENTE" ADD CONSTRAINT "PROYECTO_CLIENTE_PK" PRIMARY KEY ("COD_PROYECTO", "ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "SYS"."SUCURSAL" ADD CONSTRAINT "SUCURSAL_PK" PRIMARY KEY ("ID_SUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
