INSERT INTO EMPLOYEES 
(EMPLOYEE_ID,FIRST_NAME_LAST_NAME_EMAIL,HIRE_DATE,JOB_ID,SALARY,DEPARTMENT_ID)
VALUES
(207,‘ruben’,’sacristan’,’RSACRI’ ,’17-06-04’,SA_REP,30000,100);

INSERT INTO EMPLOYEES 
(EMPLOYEE_ID,FIRST_NAME_LAST_NAME_EMAIL,HIRE_DATE,JOB_ID,SALARY,DEPARTMENT_ID)
VALUES
(208,‘juan’,’marquez’,’juanm’ ,’18-06-04’,SA_REP,35000,100);

SAVEPOINT INSERTADO

UPDATE EMPLOYEES
SET SALARY= SALARY -1000
WHERE SALARY >20000;

UPDATE EMPLOYEES
SET DEPARTMENT_ID=110
WHERE LAST_NAME LIKE ‘ez’;

SAVEPOINT MODIFICADO

DELETE FROM EMPLOYEES
WHERE FIRST_NAME=’ruben’
AND last_name = ’sacristan’;

SELECT FROM EMPLOYEES
WHERE SALARY =30000
OR SALARY> 30000
AND DEPARTMENT_ID=110;

SAVEPOINT ELIMINADO

UPDATE EMPLOYEES
SET SALARY= (SELECT MAX_SALARY FROM JOBS
WHERE Jobs.job_id= employees.job_id);

SELECT SALARY, JOB_ID FROM EMPLOYEES;

SAVEPOINT MODIFICA_TODO

ROLLBACK TO MODIFICADO

ROLLBACK TO ELIMINADO

ROLLBACK TO INSERTADO

COMMIT



